### ISSUE TITLE
jwt:generate not working

### ISSUE THREAD

**Issue by mits87** [codecasts/laravel-jwt#10]
Hi, 

I found small bug. When I try run command `php artisan jwt:generate` then I get this error:
```
[ReflectionException]
  Method Codecasts\Auth\JWT\Console\KeyGenerateCommand::handle() does not exist
```
PS. I executed `composer dump-autoload`  before.

Could you fix it?

**Comment by hedyharto** [comment]
same problem. please advise - laravel 5.5
