### ISSUE TITLE
Error: KeyGenerateCommand::handle() does not exist

### ISSUE THREAD

**Issue by mikemillers** [codecasts/laravel-jwt#15]
When running `php artisan jwt:generate` get the following error:

`ERROR: Method Codecasts\Auth\JWT\Console\KeyGenerateCommand::handle() does not exist {"exception":"[object] (ReflectionException(code: 0): Method Codecasts\\Auth\\JWT\\Console\\KeyGenerateCommand::handle() does not exist `

Using: laravel/framework (v5.5.12) & codecasts/laravel-jwt (0.8.5)

**Comment by arturcesarmelo** [comment]
Help us, Vedovelli. I think it's a compatibillity issue with Laravel 5.5. 
Damn it!  I'm losing my mind. Had the same issue in **Tymon\JWTAuth**.

**Comment by vinicius73** [comment]
Ping @hernandev

**Comment by imikemiller** [comment]
The master branch has the `handle` method when I forked the project. But not in the version installed by composer

**Comment by adrianogl** [comment]
Fix it #17

**Comment by hernandev** [comment]
@adrianogl Please include both methods on the PR.

More details in #17 comment I just made.

A general approach will be something like this one made on [artesaos/migrator#8](https://github.com/artesaos/migrator/pull/8/files)

**Comment by hernandev** [comment]
Both methods were included to provide compatibility with both versions, so it will be released today
