### ISSUE TITLE
Erro no vendor:publish

### ISSUE THREAD

**Issue by sostenesgomes** [codecasts/laravel-jwt#2]
Ao executar php artisan vendor:publish --provider="Codecasts\Auth\JWT\ServiceProvider", surge a seguinte mensagem: Can't locate path: <0>
Publishing complete.

E não cria o arquivo de configuração em config.

Laravel 5.4.*
PHP 7.1
Ubuntu 16.04

**Comment by mrberggg** [comment]
See PR https://github.com/codecasts/laravel-jwt/pull/4

**Comment by hernandev** [comment]
fixed on #4
