### ISSUE TITLE
Package autodiscovery

### ISSUE THREAD

**Issue by joaomisturini** [codecasts/laravel-jwt#21]
Hi @hernandev!
I`m using your package with Laravel 5.5 and, despite the fix in PR #17, I was able to use it by manually adding a secret to the config file.

My question is: can I make a PR to add package autodiscovery, or should I wait until PR #17 is closed?

**Comment by hernandev** [comment]
@joaomisturini It was already solved, the thing is that I haven't released the auto discover yet, but's already there and will be included on the next release.

Thanks!

**Comment by joaomisturini** [comment]
Perfect, then. Looking forward for the release.

I mark this issue as closed.
