### ISSUE TITLE
Genarate token for never expirate

### ISSUE THREAD

**Issue by Flavioamorim** [codecasts/laravel-jwt#28]
Hi folks,

I've implemented this lib in my project, but i had a problem: i want to generate a token that never expires, but i haven't found a way to do it

thanks

**Comment by hernandev** [comment]
Just set the custom claim to null or the ttl config to a huge amount of minutes.

**Comment by hernandev** [comment]
Were you able to achieve this?

on `config/jwt.php`:

```php
    /*
    |--------------------------------------------------------------------------
    | JWT Time to live (TTL)
    |--------------------------------------------------------------------------
    |
    | ...
    |
    */
    'ttl'  => 5256000,
```

This would allow a 10 year valid token.

## Just notice, that I strongly discourage you to do it.

**Comment by Flavioamorim** [comment]
yes, thanks
