### ISSUE TITLE
Redirect to [login] when JWT isn't sent?

### ISSUE THREAD

**Issue by jokeronaldo** [codecasts/laravel-jwt#31]
I'm working under API and I don't want to dispatch a login route redirect, I just want to throw a json error message and 401 status code. Is it possible?

**Comment by hernandev** [comment]
@jokeronaldo there's a API match middleware that may be enabled to match the routes so it does not redirect, but basically it may mean you're using the web group instead of api

**Comment by jokeronaldo** [comment]
Could you provide an example?

This is my auth.php

```
    'defaults' => [
        'guard' => 'web',
        'passwords' => 'users',
    ],
    'guards' => [
        'web' => [
            'driver' => 'session',
            'provider' => 'users',
        ],

        'api' => [
            'driver' => 'jwt',
            'provider' => 'users',
        ],
    ],
```

**Comment by jokeronaldo** [comment]
My api.php route file

```
Route::middleware('auth:api')->get('/user', function (Request $request) {
    return $request->user();
});
```

**Comment by sempixel** [comment]
@jokeronaldo 

```
public function login()
    {
        $validated = request()->validate([
            'email' => 'required|email',
            'password' => 'required|string',
        ]);

        if (auth()->attempt($validated)) {
            // It's OK
        }

        return Response([], 401);
    }
```

**Comment by sempixel** [comment]
@jokeronaldo I guess you should try to listen to 

```
'Illuminate\Auth\Events\Failed' => [
        'App\Listeners\LogFailedLogin',
    ],
```

https://laravel.com/docs/5.5/authentication#events

**Comment by jokeronaldo** [comment]
@sempixel not sure if this is the right way to do that. Probably some Guard method can be override.
Suggestions?

**Comment by jokeronaldo** [comment]
I found the solution.
Laravel throw status code only over AJAX requests, so, if you are using rest clients as postman you need to pass **X-Requested-With: XMLHttpRequest** or **Accept: application/json** over headers.
Thank you @sempixel for your help.
